### ISSUE TITLE
Upgrade xUnit to 2.7.0

### ISSUE THREAD

**Issue by silkfire** [ChristophHornung/xunitmessages#1]
xUnit 2.7.0 was recently released. I can't upgrade to that version because it causes a conflict with **xunitmessages** that has a maximum version dependency on xUnit of < 2.7.0.

Could we upgrade the dependency of  **xunitmessages** to 2.7.0?

Thanks in advance!

**Comment by ChristophHornung** [comment]
@silkfire Thanks for the heads up, I updated xUnitMessages to use xUnit 2.7.0.

**Comment by silkfire** [comment]
That was blazingly fast, thank you! 🚀
